services:
  otp-app:
    build: .
    container_name: otp-breacher
    ports:
      - "5667:3000"
    env_file:
      - .env
    restart: always
    networks:
      - internal_network_dev

networks:
    internal_network_dev:
        external: true